import { useEffect, useRef, useState } from 'react';
import { ActionButton, Button, ButtonGroup, Content, defaultTheme, Dialog, DialogContainer, Divider, Heading, Item, Picker, Provider, Text } from '@adobe/react-spectrum';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, BookOpen, Box, Braces, Check, ChevronRight, Code2, Columns2, Copy, FileText, Layers3, LayoutDashboard, Moon, PanelRight, Plus, Search, Sparkles, Square, Sun, X } from 'lucide-react';
import { CATALOG_ID, definitions, type ActionDefinition } from './a2ui/catalog';
import { applyMessage, createAction, emptyRuntime, finalize, replay, writeData, type ClientAction, type Message } from './a2ui/runtime';
import { Renderer } from './a2ui/Renderer';
import { spectrumAdapter } from './adapters/spectrum';
import { demoTransport, httpTransport } from './agent/transport';
import { initialData, inferScenario, scenarioMessages, scenarios, type Scenario, type WorkspaceData } from './examples/scenarios';
import { findEquipment, money } from './examples/equipment';
import { assertWorkspaceData } from './examples/validation';

type Page = 'playground' | 'catalog' | 'guide';
type Trace = { kind: 'message' | 'action'; payload: Message | ClientAction };
const initialMessages = scenarioMessages('discover');
const icons = { discover: Search, compare: Columns2, enquiry: FileText };
const docs = [
  { label: 'Google A2UI protocol', href: 'https://a2ui.org/specification/v0.9.1-a2ui/' },
  { label: 'Adobe React Spectrum', href: 'https://react-spectrum.adobe.com/v3/getting-started.html' },
  { label: 'Source on GitHub', href: 'https://github.com/iamitesh/GenUi' },
];

export function App() {
  const [page, setPage] = useState<Page>('playground');
  const [runtime, setRuntime] = useState(() => replay(initialMessages));
  const [messages, setMessages] = useState<Message[]>(initialMessages);
  const [trace, setTrace] = useState<Trace[]>(initialMessages.map(payload => ({ kind: 'message', payload })));
  const [scenario, setScenario] = useState<Scenario>('discover');
  const [prompt, setPrompt] = useState('');
  const [mode, setMode] = useState('demo');
  const [dark, setDark] = useState(false);
  const [inspector, setInspector] = useState(false);
  const [inspectorTab, setInspectorTab] = useState<'messages' | 'data' | 'events'>('messages');
  const [busy, setBusy] = useState(false);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [revision, setRevision] = useState(0);
  const [review, setReview] = useState<WorkspaceData['request'] | null>(null);
  const [saved, setSaved] = useState<WorkspaceData['request'] | null>(null);
  const controller = useRef<AbortController | null>(null);
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => () => controller.current?.abort(), []);

  const surface = runtime.surfaces.workspace;
  const data = (surface?.data ?? initialData()) as WorkspaceData;
  const shortlist = Array.isArray(data.shortlist) ? data.shortlist : [];
  const current = scenarios.find(s => s.id === scenario)!;
  const inspectorValue = inspectorTab === 'messages' ? messages : inspectorTab === 'data' ? data : trace.filter(t => t.kind === 'action').map(t => t.payload);
  const formatted = JSON.stringify(inspectorValue, null, 2);

  async function generate(text: string, override?: WorkspaceData) {
    if (!text.trim()) return;
    controller.current?.abort();
    const task = new AbortController(); controller.current = task;
    setBusy(true); setProgress(0); setError(''); setNotice(''); setPage('playground');
    let staged = emptyRuntime();
    const batch: Message[] = [];
    try {
      const transport = mode === 'demo' ? demoTransport : httpTransport;
      for await (const message of transport.generate({ prompt: text, data: override ?? data }, task.signal)) {
        if (controller.current !== task) return;
        staged = applyMessage(staged, message); batch.push(message); setProgress(batch.length);
      }
      finalize(staged);
      if (!staged.surfaces.workspace) throw new Error('The response must contain the workspace surface.');
      assertWorkspaceData(staged.surfaces.workspace.data);
      if (controller.current !== task) return;
      setRuntime(staged); setMessages(batch); setTrace(t => [...t.slice(-47), ...batch.map(payload => ({ kind: 'message' as const, payload }))]);
      setScenario(inferScenario(text)); setRevision(v => v + 1); setPrompt('');
      setNotice(mode === 'demo' ? 'Example composed from the demo catalog.' : 'Interface generated by Gemini and validated.');
      requestAnimationFrame(() => heading.current?.focus());
    } catch (err) {
      if (controller.current === task && !task.signal.aborted) setError(err instanceof Error ? err.message : 'Generation failed.');
    } finally { if (controller.current === task) { setBusy(false); controller.current = null; } }
  }

  function change(path: string, value: unknown) {
    setRuntime(state => ({ ...state, surfaces: { ...state.surfaces, workspace: { ...state.surfaces.workspace, data: writeData(state.surfaces.workspace.data, path, value) } } }));
  }

  function action(id: string, definition: ActionDefinition) {
    try {
      const event = createAction(surface, id, definition);
      setTrace(t => [...t.slice(-49), { kind: 'action', payload: event }]);
      const { name, context } = event.action;
      if (name === 'shortlist.toggle') {
        const id = String(context.equipmentId);
        change('/shortlist', shortlist.includes(id) ? shortlist.filter(x => x !== id) : [...shortlist, id]);
      } else if (name === 'equipment.compare') {
        if (shortlist.length < 2) { setError('Select at least two machines to compare.'); return; }
        void generate(scenarios[1].prompt);
      } else if (name === 'enquiry.open') {
        const next = structuredClone(data); next.request.equipment = findEquipment(context.equipmentId).id;
        void generate(scenarios[2].prompt, next);
      } else if (name === 'enquiry.review') {
        const r = data.request;
        if (!r || !r.name?.trim() || !r.location?.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(r.email ?? '') || !Number.isFinite(r.days) || r.days < 1 || r.days > 90 || !r.consent) { setError('Add your name, a valid email, location, 1–90 rental days, and acknowledge the illustrative rates.'); return; }
        setError(''); setReview(structuredClone(r));
      }
    } catch (err) { setError(err instanceof Error ? err.message : 'The action could not be completed.'); }
  }

  function reset() {
    controller.current?.abort(); controller.current = null;
    setBusy(false); setRuntime(replay(initialMessages)); setMessages(initialMessages);
    setTrace(initialMessages.map(payload => ({ kind: 'message', payload }))); setScenario('discover');
    setRevision(v => v + 1); setPage('playground'); setError(''); setNotice('New workspace ready.'); setPrompt(''); setSaved(null);
  }
  function download() {
    const snapshot = [
      { version: 'v0.9.1', createSurface: { surfaceId: surface.id, catalogId: surface.catalogId, ...(surface.theme ? { theme: surface.theme } : {}) } },
      { version: 'v0.9.1', updateDataModel: { surfaceId: surface.id, value: surface.data } },
      { version: 'v0.9.1', updateComponents: { surfaceId: surface.id, components: Object.values(surface.components) } },
    ];
    const blob = new Blob([JSON.stringify(snapshot, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `genui-${scenario}.a2ui.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  return <Provider theme={defaultTheme} colorScheme={dark ? 'dark' : 'light'} locale="en-IN"><div className={`app ${dark ? 'dark' : ''}`}>
    <a className="skip-link" href="#main">Skip to workspace</a>
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e => { e.preventDefault(); setPage('playground'); }}><span className="brand-mark"><Layers3 size={22} /></span><span>GenUI <b>Studio</b></span><span className="lab-pill">LAB</span></a>
      <button className="new-workspace" onClick={reset}><Plus size={17} /> New workspace <span>↗</span></button>
      <p className="nav-label">WORKSPACE</p>
      <nav aria-label="Main navigation">
        {([{ id: 'playground', name: 'Playground', icon: LayoutDashboard }, { id: 'catalog', name: 'Component catalog', icon: Box }, { id: 'guide', name: 'Integration guide', icon: BookOpen }] as const).map(item => <button key={item.id} className={`nav-item ${page === item.id ? 'active' : ''}`} onClick={() => setPage(item.id)} aria-current={page === item.id ? 'page' : undefined}><item.icon size={18} />{item.name}{item.id === 'catalog' ? <small>{Object.keys(definitions).length}</small> : null}</button>)}
      </nav>
      <p className="nav-label examples-label">EXAMPLE FLOWS</p>
      <div className="sidebar-examples">{scenarios.map((s, i) => <button key={s.id} disabled={busy} onClick={() => void generate(s.prompt)}><span>0{i + 1}</span>{s.label}</button>)}</div>
      <div className="sidebar-bottom"><div className="adapter-status"><span className="status-dot" /><div><strong>Adobe Spectrum</strong><small>Connected design system</small></div><Layers3 size={16} /></div><div className="sidebar-user"><span className="avatar">A</span><div><strong>Amitesh’s workspace</strong><small>Generative UI exploration</small></div></div></div>
    </aside>
    <div className="main-layout">
      <header className="topbar"><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14} /><strong>{page === 'playground' ? 'Playground' : page === 'catalog' ? 'Component catalog' : 'Integration guide'}</strong></div><div className="top-actions"><span className="protocol-pill">A2UI v0.9.1</span><ActionButton aria-label={dark ? 'Use light theme' : 'Use dark theme'} isQuiet onPress={() => setDark(!dark)}>{dark ? <Sun size={17} /> : <Moon size={17} />}</ActionButton><a className="github-link" href="https://github.com/iamitesh/GenUi" target="_blank" rel="noreferrer">View source <ArrowUpRight size={15} /></a></div></header>
      <main id="main">
        {page === 'playground' ? <>
          <section className="intro"><div className="eyebrow"><span />YOUR INTENT. A NEW INTERFACE.</div><h1>What would you like to <em>build?</em></h1><p>Describe a task. Watch it become an interface, powered by your design system.</p></section>
          <form className={`composer ${busy ? 'generating' : ''}`} onSubmit={e => { e.preventDefault(); void generate(prompt); }}>
            <label htmlFor="prompt" className="sr-only">Describe your interface</label><div className="prompt-row"><Sparkles size={22} aria-hidden="true" /><textarea id="prompt" value={prompt} maxLength={2000} rows={2} disabled={busy} onChange={e => setPrompt(e.target.value)} placeholder="Find excavators for a two-week project in Bengaluru…" onKeyDown={e => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') { e.preventDefault(); void generate(prompt); } }} /></div>
            <div className="composer-footer"><div className="composer-options"><span className="system-chip"><span className="spectrum-symbol">S</span>Adobe Spectrum</span><Picker aria-label="Generation mode" selectedKey={mode} isDisabled={busy} onSelectionChange={key => setMode(String(key))} width={170}><Item key="demo">Demo generator</Item><Item key="gemini">Gemini · API key</Item></Picker></div>{busy ? <Button variant="secondary" onPress={() => { controller.current?.abort(); controller.current = null; setBusy(false); setNotice('Generation stopped. Your previous design is preserved.'); }}><Square size={13} /><Text>Stop</Text></Button> : <Button type="submit" variant="accent" isDisabled={!prompt.trim()}><Text>Generate interface</Text><ArrowRight size={16} /></Button>}</div>
          </form>
          <div className="mode-note"><span className="status-dot" />{mode === 'demo' ? 'Demo mode · three curated flows, no model calls or API key' : 'Gemini mode · sends your prompt and workspace data to the model via the local server'}</div>
          <div className="suggestions">{scenarios.map(s => { const Icon = icons[s.id]; return <button key={s.id} disabled={busy} className={scenario === s.id ? 'chosen' : ''} onClick={() => void generate(s.prompt)}><span className={`suggestion-icon icon-${s.id}`}><Icon size={20} /></span><span><strong>{s.label}</strong><small>{s.description}</small></span><ArrowUpRight size={16} /></button>; })}</div>
          {error ? <div role="alert" className="alert error"><span>{error}</span><button aria-label="Dismiss error" onClick={() => setError('')}><X size={16} /></button></div> : null}
          <div className="sr-only" role="status" aria-live="polite">{busy ? `Validating message ${progress}.` : notice}</div>
          <section className="workspace-section" aria-busy={busy}><div className="workspace-toolbar"><div><span className="canvas-dot" /><h2 ref={heading} tabIndex={-1}>Live canvas</h2><span className="canvas-label">{current.short}</span></div><div><span className="validated-label"><Check size={13} />{busy ? `${progress} messages received` : 'Schema validated'}</span><ActionButton isQuiet aria-label="Download A2UI JSON" onPress={download}><ArrowDownToLine size={16} /></ActionButton><ActionButton isQuiet aria-label="Toggle protocol inspector" aria-pressed={inspector} onPress={() => setInspector(!inspector)}><PanelRight size={17} /><Text>Inspect</Text></ActionButton></div></div>
            <div className={`canvas-layout ${inspector ? 'with-inspector' : ''}`}><div className={`canvas ${busy ? 'canvas-busy' : ''}`} inert={busy}><div className="canvas-topline"><span><span className="mini-brand"><Layers3 size={15} /></span>TERRA / RENTAL WORKSPACE</span><span className="fixture-badge">SAMPLE DATA</span></div>{surface ? <Renderer revision={revision} surface={surface} adapter={spectrumAdapter} onChange={change} onAction={action} /> : <p>Choose an example to create a surface.</p>}<div className="canvas-footnote"><span>Rendered with Adobe Spectrum</span><span>{Object.keys(surface?.components ?? {}).length} components · {messages.length} A2UI messages</span></div></div>
            {inspector ? <aside className="inspector" aria-label="Protocol inspector"><div className="inspector-heading"><Braces size={17} /><strong>Under the surface</strong><button onClick={() => setInspector(false)} aria-label="Close inspector"><X size={16} /></button></div><div className="inspector-tabs" role="group" aria-label="Inspector views">{(['messages', 'data', 'events'] as const).map(tab => <button id={`tab-${tab}`} aria-controls="inspector-panel" aria-pressed={inspectorTab === tab} key={tab} onClick={() => setInspectorTab(tab)}>{tab}</button>)}</div><div className="code-toolbar"><span>{inspectorTab === 'messages' ? 'server → client' : inspectorTab === 'events' ? 'client → handler' : 'local data model'}</span><button aria-label="Copy inspector JSON" onClick={() => { void navigator.clipboard.writeText(formatted).then(() => setNotice('Copied JSON to clipboard.')).catch(() => setError('Clipboard unavailable. Use Download A2UI JSON instead.')); }}><Copy size={14} /></button></div><pre id="inspector-panel" role="region" aria-labelledby={`tab-${inspectorTab}`} tabIndex={0}>{formatted}</pre><p>Validated envelopes + a versioned catalog. The renderer selects registered components.</p></aside> : null}</div>
          </section>
          <div className="workspace-bottom"><span><Code2 size={14} /> One catalog. Many possible interfaces.</span><button onClick={() => setPage('guide')}>How it works <ArrowRight size={14} /></button></div>
          {saved ? <div className="alert success" role="status"><Check size={17} /><span>Draft saved for {saved.name} · {saved.location} · {saved.days} days. Available in this session; nothing sent.</span><Button variant="secondary" onPress={() => setReview(saved)}>View draft</Button></div> : null}
        </> : page === 'catalog' ? <section className="reference-page"><div className="eyebrow">THE BUILDING BLOCKS</div><h1>A shared language for UI.</h1><p>These {Object.keys(definitions).length} components form the application catalog. Adobe Spectrum supplies the controls and interaction behavior.</p><div className="adapter-grid"><div className="adapter-card"><span className="spectrum-symbol">S</span><h3>Adobe Spectrum</h3><p>Implemented · React Spectrum v3</p><span className="tag live">Active adapter</span></div>{['shadcn/ui', 'Material UI'].map(name => <div className="adapter-card future" key={name}><Box size={27} /><h3>{name}</h3><p>Future adapter · not implemented</p><span className="tag">Extension point ready</span></div>)}</div><div className="catalog-grid">{Object.entries(definitions).map(([name, def]) => <article className="catalog-item" key={name}><code>{name}</code><p>{def.description}</p><small>Required: {def.required.join(', ') || 'id, component only'}</small></article>)}</div><p className="catalog-id">Catalog ID: <code>{CATALOG_ID}</code></p></section> : <section className="reference-page"><div className="eyebrow">FROM INTENT TO INTERFACE</div><h1>Built to change design systems.</h1><p>The agent describes the interface. A validated catalog gives those descriptions meaning. Your adapter renders real components.</p><div className="guide-steps">{[{ n: '01', title: 'Describe the intent', detail: 'Choose a deterministic example, or configure Gemini in .env.local and start the local development server.' }, { n: '02', title: 'Generate A2UI messages', detail: 'Create a surface, supply data, and compose registered components using a flat list of stable IDs.' }, { n: '03', title: 'Validate, then render', detail: 'The original A2UI v0.9.1 envelope schema and our custom catalog reject unsupported props, actions, and invalid component graphs.' }, { n: '04', title: 'Keep the conversation interactive', detail: 'Fields write to the local model. Explicit actions carry resolved context to handlers. Your selections and request travel between example flows.' }].map(step => <article key={step.n}><span>{step.n}</span><div><h3>{step.title}</h3><p>{step.detail}</p></div></article>)}</div><div className="guide-callout"><Layers3 size={26} /><div><h3>Bring your next design system</h3><p>Implement DesignSystemAdapter, map every catalog component to shadcn/ui or MUI, then wrap the renderer in its theme provider. The message format and agent stay the same.</p></div></div><p className="guide-limit">This is a custom, deliberately limited A2UI renderer. It is not the Google renderer SDK or full Basic Catalog implementation. Relative bindings, functions, and automatic full-model synchronization are outside this sample.</p><div className="doc-links">{docs.map(doc => <a key={doc.href} href={doc.href} target="_blank" rel="noreferrer">{doc.label}<ArrowUpRight size={16} /></a>)}</div></section>}
      </main><footer className="app-footer"><span>GenUI Studio <span>·</span> An interface for every intent.</span><span>A2UI protocol + Adobe Spectrum</span></footer>
    </div>
    <DialogContainer onDismiss={() => setReview(null)}>{review ? <Dialog><Heading>Review your enquiry</Heading><Divider /><Content><p className="review-intro">This will save a local session draft. It does not contact a dealer.</p><dl className="review-details"><dt>Machine</dt><dd>{findEquipment(review.equipment).name}</dd><dt>Location</dt><dd>{review.location}</dd><dt>Duration</dt><dd>{review.days} days</dd><dt>Contact</dt><dd>{review.name} · {review.email}</dd><dt>Sample base estimate</dt><dd>{money(findEquipment(review.equipment).dayRate * review.days)}</dd></dl><p>Taxes, transport, fuel and operator charges are excluded. Availability needs confirmation.</p></Content><ButtonGroup><Button variant="secondary" onPress={() => setReview(null)}>Back to editing</Button><Button variant="accent" onPress={() => { setSaved(review); setReview(null); setNotice('Local enquiry draft saved. Nothing was sent.'); }}>Save local draft</Button></ButtonGroup></Dialog> : null}</DialogContainer>
  </div></Provider>;
}
